### ISSUE TITLE
LLaVA weights

### ISSUE THREAD

**Issue by 1997MarsRover** [Evahns/VizuoSense#46]
Has anyone downloaded the text model and the vision model?. IF not have a look at this [LLaVA](https://github.com/haotian-liu/LLaVA) i think if we have the weights we can run the model locally while prompting the assistant

**Comment by 1997MarsRover** [comment]
```

### CLI Inference

Chat about images using LLaVA without the need of Gradio interface. It also supports multiple GPUs, 4-bit and 8-bit quantized inference. With 4-bit quantization, for our LLaVA-1.5-7B, it uses less than 8GB VRAM on a single GPU.

```Shell
python -m llava.serve.cli \
    --model-path liuhaotian/llava-v1.5-7b \
    --image-file "https://llava-vl.github.io/static/images/view.jpg" \
    --load-4bit
```

<img src="Resources/demo_cli.gif" width="70%">

**Comment by Evahns** [comment]
thanks for the heads up @1997MarsRover  , check this out also  @AlvinKimata and @shabtai261
